---
sudo: required
dist: trusty

services:
  - docker

before_install:
  - SCALA_VERSION=2.11
  - KAFKA_VERSION=0.10.1.0
  - wget http://www.us.apache.org/dist/kafka/$KAFKA_VERSION/kafka_$SCALA_VERSION-$KAFKA_VERSION.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1

script:
  # Build docker image
  - docker build -t maestrano/kafka:travis ./0.10 > /dev/null 2>&1

  # Configuration
  - HOST_PUB_IP=$(ifconfig | grep "eth0 " -A 1 | grep "inet " | cut -d':' -f2 | cut -d' ' -f1)
  - ZK_PORT_NODE=2181
  - KAFKA_PORT_NODE=9092
  - KAFKA=$HOST_PUB_IP:$KAFKA_PORT_NODE
  - ZOOKEEPER=$HOST_PUB_IP:$ZK_PORT_NODE/kafka

  #============================================================================
  # Test standalone Kafka
  #============================================================================
  # Start standalone instance
  - docker run -d -p $ZK_PORT_NODE:2181 -p $KAFKA_PORT_NODE:9092 -e SELF_HOST=$HOST_PUB_IP -e SELF_PORT=$KAFKA_PORT_NODE -e ZK_CHROOT=kafka --name k0 maestrano/kafka:travis

  # Wait for instance to be up (via Docker healthcheck)
  - for i in {30..0}; do HEALTH_CHECK=$(docker inspect --format='{{.State.Health.Status}}' k0 2>/dev/null); [ "$HEALTH_CHECK" == "running" ] && break; sleep 1; done

  # Create a topic
  - "topic=$(kafka/bin/kafka-topics.sh --create --zookeeper $ZOOKEEPER -replication-factor 1 --partitions 1 --topic eventstopic)"
  - '[ "$topic" == "Created topic \"eventstopic\"." ]'

  # Create an event in this topic and read it
  - echo "myevent" | kafka/bin/kafka-console-producer.sh --broker-list $KAFKA --topic eventstopic
  - "events=$(kafka/bin/kafka-console-consumer.sh --bootstrap-server $KAFKA --topic eventstopic --from-beginning --timeout-ms 15000)"
  - '[ "$events" == "myevent" ]'

  # Terminate redis
  - docker rm -f k0
  