---
sudo: required
dist: trusty

services:
  - docker

script:
  # Build docker image
  - docker build -t docker-kafka ./0.10 > /dev/null 2>&1

  # Configuration
  - HOST_PUB_IP=$(ifconfig | grep "eth0 " -A 1 | grep "inet " | cut -d':' -f2 | cut -d' ' -f1)
  - ZK_PORT_NODE=2181
  - KAFKA_PORT_NODE=9092

  #============================================================================
  # Test standalone Redis
  #============================================================================
  # Start standalone instance
  - docker run -d -p $ZK_PORT_NODE:2181 -p $KAFKA_PORT_NODE:9092 -e ZK_CHROOT=kafka --name k0 docker-kafka

  # Wait for instance to be up (via Docker healthcheck)
  - for i in {30..0}; do HEALTH_CHECK=$(docker inspect --format='{{.State.Health.Status}}' k0 2>/dev/null); [ "$HEALTH_CHECK" == "running" ] && break; sleep 1; done

  # Terminate redis
  - docker rm -f k0
  